### ISSUE TITLE
composer error

### ISSUE THREAD

**Issue by VickG** [sroutier/l51esk-modules#2]
When running composer update, I am getting following error..any ideas?

Exception: Class modules does not exist
Skipping \Sroutier\LESKModules\Facades\Module.

**Comment by VickG** [comment]
```
ubuntu@staging:/var/www/html$ composer require sroutier/lesk-modules
Using version 3.0.7.13 for sroutier/lesk-modules                         
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)                            
  - Installing sroutier/lesk-modules (3.0.7.13)
    Downloading: 100%         

sroutier/lesk-modules suggests installing wikimedia/composer-merge-plugin (Allows the ability to create and merge composer.json files for your individual modules for module-specific dependency management.)
Writing lock file
Generating autoload files
> php artisan clear-compiled
> php artisan ide-helper:generate
Exception: Class modules does not exist
Skipping \Sroutier\LESKModules\Facades\Module.
A new helper file was written to _ide_helper.php
> php artisan optimize
Generating optimized class loader
ubuntu@staging:/var/www/html$ 

```

**Comment by sroutier** [comment]
Humm... Not sure.

Do you have the latest code?
Are you using any modules?
Can you send the whole stack trace? That way I can try to see where it gets
triggered.

I'll try to run a composer update in the morning to see if it all works for
me and let you know.

/s

**Comment by sroutier** [comment]
Hello @VickG,

I just tried on a clean and new Laravel 5.1 project, see below, and it all worked perfectly:

```
[sroutier@vmweb01 l51test]$ composer require sroutier/lesk-modules
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Using version 3.0.7.13 for sroutier/lesk-modules
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing sroutier/lesk-modules (3.0.7.13)
    Loading from cache

sroutier/lesk-modules suggests installing wikimedia/composer-merge-plugin (Allows the ability to create and merge composer.json files for your individual modules for module-specific dependency management.)
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan ide-helper:generate
A new helper file was written to _ide_helper.php
> php artisan ide-helper:meta
A new meta file was written to .phpstorm.meta.php
> php artisan optimize
Generating optimized class loader
[sroutier@vmweb01 l51test]$ 
```

Can you describe your project and environment a little. Here are the commands that I ran from zero to base project newly created with module required:

```
$ composer create-project laravel/laravel l51test "5.1.*"
$ cd l51test/
$ composer require barryvdh/laravel-ide-helper
$ touch database/database.sqlite
$ composer require sroutier/lesk-modules
```

One thing that looks a little strange in your output is the case of the class name that it complains about:

```
Exception: Class modules does not exist
```

The facade is called "Module", with a capital `M` and in the singular form, meaning no `s`, the main class is called "Modules" with a capital `M`. Why would the error have a lower case 'm' ?? Is that one of your classes? It would be unfortunate if artisan or the ide-helper package adjusted the case to make the sentence prettier.

Hopefully this helps you a little. Let me know what you think.

Cheers.
/S

**Comment by VickG** [comment]
my apologies. It was a different package trying to load right before this package that had the error. 

Composer was not very clear on what package had the error, so I assume it was the package that it skipped

> Exception: Class modules does not exist
> Skipping \Sroutier\LESKModules\Facades\Module.

But since then, I have learned that is the preceding package that has the error, and it skipped the Module package since the previous one failed.

I am closing this ticket.

**Comment by sroutier** [comment]
👍
